/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sharepricegraph;

import com.sun.javafx.css.CssError;

/**
 *
 * @author Toby
 */
public class gameScreen extends javax.swing.JFrame {

    public static int[] stockValues = new int[3];
    public static int[] numOfStocks = new int[3];
    public static int[] valueOfOwendStocks = new int[3];
    public static int totalStockCount;
    public static int totalValueOfOwnedStocks;
    public static int totalMoney = 100;

    /**
     * Creates new form gameScreen
     */
    public gameScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sellAppool = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buyAppool = new javax.swing.JButton();
        amazoonStocksNumber = new javax.swing.JLabel();
        sellMicrosooft = new javax.swing.JButton();
        buyMicrosooft = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sellAmazoon = new javax.swing.JButton();
        buyAmazoon = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalStocksNumber = new javax.swing.JLabel();
        microsooftStocksNumber = new javax.swing.JLabel();
        yourAppoolStocksValue = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        appoolStocksNumber = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        yourMicrosooftStocksValue = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        yourAmazoonStocksValue = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        moneyToT = new javax.swing.JLabel();
        money3 = new javax.swing.JLabel();
        totalStockValue = new javax.swing.JLabel();
        money1 = new javax.swing.JLabel();
        appoolStockValue = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        microsooftStockValue = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        amazoonStockValue = new javax.swing.JLabel();
        money2 = new javax.swing.JLabel();
        appoolStocksValue1 = new javax.swing.JLabel();
        appoolStocksValue2 = new javax.swing.JLabel();
        appoolStocksValue3 = new javax.swing.JLabel();
        buyAppool1 = new javax.swing.JButton();
        buyMicrosooft1 = new javax.swing.JButton();
        buyAmazoon1 = new javax.swing.JButton();
        sellMicrosooft1 = new javax.swing.JButton();
        sellMicrosooft2 = new javax.swing.JButton();
        sellMicrosooft3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sellAppool.setBackground(new java.awt.Color(255, 204, 204));
        sellAppool.setForeground(new java.awt.Color(51, 51, 51));
        sellAppool.setText("SELL");
        sellAppool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellAppoolActionPerformed(evt);
            }
        });
        getContentPane().add(sellAppool, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("MICROSOOFT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 160, 40));

        buyAppool.setBackground(new java.awt.Color(204, 255, 204));
        buyAppool.setForeground(new java.awt.Color(51, 51, 51));
        buyAppool.setText("BUY");
        buyAppool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyAppoolActionPerformed(evt);
            }
        });
        getContentPane().add(buyAppool, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, 30));

        amazoonStocksNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        amazoonStocksNumber.setForeground(new java.awt.Color(102, 153, 0));
        amazoonStocksNumber.setText("0");
        getContentPane().add(amazoonStocksNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 40, 20));

        sellMicrosooft.setBackground(new java.awt.Color(255, 204, 204));
        sellMicrosooft.setForeground(new java.awt.Color(51, 51, 51));
        sellMicrosooft.setText("SELL");
        sellMicrosooft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellMicrosooftActionPerformed(evt);
            }
        });
        getContentPane().add(sellMicrosooft, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 90, 30));

        buyMicrosooft.setBackground(new java.awt.Color(204, 255, 204));
        buyMicrosooft.setForeground(new java.awt.Color(51, 51, 51));
        buyMicrosooft.setText("BUY");
        buyMicrosooft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyMicrosooftActionPerformed(evt);
            }
        });
        getContentPane().add(buyMicrosooft, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Total stock value:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 120, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("APPOOL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("AMAZOON");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 140, 40));

        sellAmazoon.setBackground(new java.awt.Color(255, 204, 204));
        sellAmazoon.setForeground(new java.awt.Color(51, 51, 51));
        sellAmazoon.setText("SELL");
        sellAmazoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellAmazoonActionPerformed(evt);
            }
        });
        getContentPane().add(sellAmazoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, 30));

        buyAmazoon.setBackground(new java.awt.Color(204, 255, 204));
        buyAmazoon.setForeground(new java.awt.Color(51, 51, 51));
        buyAmazoon.setText("BUY");
        buyAmazoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyAmazoonActionPerformed(evt);
            }
        });
        getContentPane().add(buyAmazoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 90, 30));

        jLabel6.setText("Amazoon Stocks:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 110, 20));

        jLabel7.setText("Microsooft Stocks:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 110, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Total stocks:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 90, 20));

        jLabel9.setText("stocks:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 30));

        totalStocksNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalStocksNumber.setForeground(new java.awt.Color(102, 102, 102));
        totalStocksNumber.setText("0");
        getContentPane().add(totalStocksNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 50, 20));

        microsooftStocksNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        microsooftStocksNumber.setForeground(new java.awt.Color(204, 153, 0));
        microsooftStocksNumber.setText("0");
        getContentPane().add(microsooftStocksNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 40, 20));

        yourAppoolStocksValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yourAppoolStocksValue.setForeground(new java.awt.Color(102, 102, 102));
        yourAppoolStocksValue.setText("0");
        getContentPane().add(yourAppoolStocksValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 40, 20));

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Stock Value:   £");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 30));

        jLabel15.setText("Value of your ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 20));

        appoolStocksNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        appoolStocksNumber.setForeground(new java.awt.Color(204, 51, 0));
        appoolStocksNumber.setText("0");
        getContentPane().add(appoolStocksNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 40, 20));

        jLabel17.setText("Value of your ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 90, 20));

        jLabel18.setText("stocks:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 90, 30));

        yourMicrosooftStocksValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yourMicrosooftStocksValue.setForeground(new java.awt.Color(102, 102, 102));
        yourMicrosooftStocksValue.setText("0");
        getContentPane().add(yourMicrosooftStocksValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 40, 20));

        jLabel20.setText("Value of your ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 90, 20));

        jLabel21.setText("stocks:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 90, 30));

        yourAmazoonStocksValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yourAmazoonStocksValue.setForeground(new java.awt.Color(102, 102, 102));
        yourAmazoonStocksValue.setText("0");
        getContentPane().add(yourAmazoonStocksValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 40, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jPanel1.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Money:");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(80, 50, 52, 20);

        moneyToT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        moneyToT.setForeground(new java.awt.Color(102, 102, 102));
        moneyToT.setText("100");
        jPanel1.add(moneyToT);
        moneyToT.setBounds(140, 50, 50, 20);

        money3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        money3.setForeground(new java.awt.Color(102, 102, 102));
        money3.setText("£");
        jPanel1.add(money3);
        money3.setBounds(130, 50, 17, 20);

        totalStockValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalStockValue.setForeground(new java.awt.Color(102, 102, 102));
        totalStockValue.setText("0");
        jPanel1.add(totalStockValue);
        totalStockValue.setBounds(140, 30, 50, 20);

        money1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        money1.setForeground(new java.awt.Color(102, 102, 102));
        money1.setText("£");
        jPanel1.add(money1);
        money1.setBounds(130, 30, 17, 20);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 190, 80));

        appoolStockValue.setForeground(new java.awt.Color(102, 102, 102));
        appoolStockValue.setText("1");
        getContentPane().add(appoolStockValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 60, 30));

        jLabel16.setText("Appool Stocks:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 20));

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Stock Value:   £");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 90, 30));

        microsooftStockValue.setForeground(new java.awt.Color(102, 102, 102));
        microsooftStockValue.setText("1");
        getContentPane().add(microsooftStockValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 60, 30));

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Stock Value:   £");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 90, 30));

        amazoonStockValue.setForeground(new java.awt.Color(102, 102, 102));
        amazoonStockValue.setText("1");
        getContentPane().add(amazoonStockValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 60, 30));

        money2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        money2.setForeground(new java.awt.Color(102, 102, 102));
        money2.setText("0");
        getContentPane().add(money2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 30, 20));

        appoolStocksValue1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        appoolStocksValue1.setForeground(new java.awt.Color(102, 102, 102));
        appoolStocksValue1.setText("£");
        getContentPane().add(appoolStocksValue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 10, 20));

        appoolStocksValue2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        appoolStocksValue2.setForeground(new java.awt.Color(102, 102, 102));
        appoolStocksValue2.setText("£");
        getContentPane().add(appoolStocksValue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 10, 20));

        appoolStocksValue3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        appoolStocksValue3.setForeground(new java.awt.Color(102, 102, 102));
        appoolStocksValue3.setText("£");
        getContentPane().add(appoolStocksValue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 10, 20));

        buyAppool1.setBackground(new java.awt.Color(204, 255, 204));
        buyAppool1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(buyAppool1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, 30));

        buyMicrosooft1.setBackground(new java.awt.Color(204, 255, 204));
        buyMicrosooft1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(buyMicrosooft1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 90, 30));

        buyAmazoon1.setBackground(new java.awt.Color(204, 255, 204));
        buyAmazoon1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(buyAmazoon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 90, 30));

        sellMicrosooft1.setBackground(new java.awt.Color(255, 204, 204));
        sellMicrosooft1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(sellMicrosooft1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, 30));

        sellMicrosooft2.setBackground(new java.awt.Color(255, 204, 204));
        sellMicrosooft2.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(sellMicrosooft2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 90, 30));

        sellMicrosooft3.setBackground(new java.awt.Color(255, 204, 204));
        sellMicrosooft3.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(sellMicrosooft3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sellAppoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellAppoolActionPerformed
        performSell(0);
        yourAppoolStocksValue.setText(String.valueOf(valueOfOwendStocks[0]));
        appoolStocksNumber.setText(String.valueOf(numOfStocks[0]));
    }//GEN-LAST:event_sellAppoolActionPerformed

    private void buyAppoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyAppoolActionPerformed
        performBuy(0);
        yourAppoolStocksValue.setText(String.valueOf(valueOfOwendStocks[0]));
        appoolStocksNumber.setText(String.valueOf(numOfStocks[0]));
    }//GEN-LAST:event_buyAppoolActionPerformed

    private void sellMicrosooftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellMicrosooftActionPerformed
        performSell(1);
        yourMicrosooftStocksValue.setText(String.valueOf(valueOfOwendStocks[1]));
        microsooftStocksNumber.setText(String.valueOf(numOfStocks[1]));
    }//GEN-LAST:event_sellMicrosooftActionPerformed

    private void buyMicrosooftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyMicrosooftActionPerformed
        performBuy(1);
        yourMicrosooftStocksValue.setText(String.valueOf(valueOfOwendStocks[1]));
        microsooftStocksNumber.setText(String.valueOf(numOfStocks[1]));
    }//GEN-LAST:event_buyMicrosooftActionPerformed

    private void sellAmazoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellAmazoonActionPerformed
        performSell(2);
        yourAmazoonStocksValue.setText(String.valueOf(valueOfOwendStocks[2]));
        amazoonStocksNumber.setText(String.valueOf(numOfStocks[2]));
    }//GEN-LAST:event_sellAmazoonActionPerformed

    private void buyAmazoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyAmazoonActionPerformed
        performBuy(2);
        yourAmazoonStocksValue.setText(String.valueOf(valueOfOwendStocks[2]));
        amazoonStocksNumber.setText(String.valueOf(numOfStocks[2]));
    }//GEN-LAST:event_buyAmazoonActionPerformed

    public static void performBuy(int companyNum) {
        if (totalMoney >= stockValues[companyNum]) {
            totalMoney -= stockValues[companyNum];
            numOfStocks[companyNum]++;
            totalStockCount++;
            totalValueOfOwnedStocks += stockValues[companyNum];
            valueOfOwendStocks[companyNum] += stockValues[companyNum];

            moneyToT.setText(String.valueOf(totalMoney));
            totalStocksNumber.setText(String.valueOf(totalStockCount));
            totalStockValue.setText(String.valueOf(totalValueOfOwnedStocks));
        }
        inableDisableBuyButtons();
    }

    public static void performSell(int companyNum) {
        if (numOfStocks[companyNum] > 0) {
            totalMoney += stockValues[companyNum];
            numOfStocks[companyNum]--;
            totalStockCount--;
            totalValueOfOwnedStocks -= stockValues[companyNum];
            valueOfOwendStocks[companyNum] -= stockValues[companyNum];

            moneyToT.setText(String.valueOf(totalMoney));
            totalStocksNumber.setText(String.valueOf(totalStockCount));
            totalStockValue.setText(String.valueOf(totalValueOfOwnedStocks));
        }
        inableDisableBuyButtons();
    }

    public static void UpdateStockValues(int appoolValue, int microsooftValue, int amazoonValue) {
        appoolStockValue.setText(String.valueOf(appoolValue));
        microsooftStockValue.setText(String.valueOf(microsooftValue));
        amazoonStockValue.setText(String.valueOf(amazoonValue));

        valueOfOwendStocks[0] = appoolValue*numOfStocks[0];
        yourAppoolStocksValue.setText(String.valueOf(valueOfOwendStocks[0]));
        valueOfOwendStocks[1] = microsooftValue* numOfStocks[1];
        yourMicrosooftStocksValue.setText(String.valueOf(valueOfOwendStocks[1]));
        valueOfOwendStocks[2] = amazoonValue* numOfStocks[2];
        yourAmazoonStocksValue.setText(String.valueOf(valueOfOwendStocks[2]));

        totalValueOfOwnedStocks = valueOfOwendStocks[0] + valueOfOwendStocks[1] + valueOfOwendStocks[2];
        totalStockValue.setText(String.valueOf(totalValueOfOwnedStocks));

        inableDisableBuyButtons();
    }

    public static void inableDisableBuyButtons() {
        if (stockValues[0] > totalMoney || stockValues[0] == 0) {
            buyAppool.setVisible(false);
        } else {
            buyAppool.setVisible(true);
        }
        if (stockValues[1] > totalMoney || stockValues[1] == 0) {
            buyMicrosooft.setVisible(false);
        } else {
            buyMicrosooft.setVisible(true);
        }
        if (stockValues[2] > totalMoney || stockValues[2] == 0) {
            buyAmazoon.setVisible(false);
        } else {
            buyAmazoon.setVisible(true);
        }
        
        if(numOfStocks[0] < 1){
            sellAppool.setVisible(false);
        }else{
            sellAppool.setVisible(true);
        }
        if(numOfStocks[1] < 1){
            sellMicrosooft.setVisible(false);
        }else{
            sellMicrosooft.setVisible(true);
        }
        if(numOfStocks[2] < 1){
            sellAmazoon.setVisible(false);
        }else{
            sellAmazoon.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel amazoonStockValue;
    public static javax.swing.JLabel amazoonStocksNumber;
    public static javax.swing.JLabel appoolStockValue;
    public static javax.swing.JLabel appoolStocksNumber;
    private javax.swing.JLabel appoolStocksValue1;
    private javax.swing.JLabel appoolStocksValue2;
    private javax.swing.JLabel appoolStocksValue3;
    public static javax.swing.JButton buyAmazoon;
    public static javax.swing.JButton buyAmazoon1;
    public static javax.swing.JButton buyAppool;
    public static javax.swing.JButton buyAppool1;
    public static javax.swing.JButton buyMicrosooft;
    public static javax.swing.JButton buyMicrosooft1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel microsooftStockValue;
    public static javax.swing.JLabel microsooftStocksNumber;
    private javax.swing.JLabel money1;
    private javax.swing.JLabel money2;
    private javax.swing.JLabel money3;
    public static javax.swing.JLabel moneyToT;
    public static javax.swing.JButton sellAmazoon;
    public static javax.swing.JButton sellAppool;
    public static javax.swing.JButton sellMicrosooft;
    public static javax.swing.JButton sellMicrosooft1;
    public static javax.swing.JButton sellMicrosooft2;
    public static javax.swing.JButton sellMicrosooft3;
    public static javax.swing.JLabel totalStockValue;
    public static javax.swing.JLabel totalStocksNumber;
    public static javax.swing.JLabel yourAmazoonStocksValue;
    public static javax.swing.JLabel yourAppoolStocksValue;
    public static javax.swing.JLabel yourMicrosooftStocksValue;
    // End of variables declaration//GEN-END:variables
}
